{{- if .Values.ingressRoute.enabled }}
{{- $fullName := include "warden.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - match: {{ .match }}
      kind: {{ .kind | default "Rule" }}
      {{- with .middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      services:
        {{- if .services }}
        {{- toYaml .services | nindent 8 }}
        {{- else }}
        - name: {{ $fullName }}
          port: {{ $.Values.service.port }}
        {{- end }}
    {{- end }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
