{{- if include "warden.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warden.fullname" . }}
  labels:
    {{- include "warden.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  {{- if and (eq .Values.database.type "postgres") .Values.database.external.enabled .Values.database.external.url (not .Values.database.external.existingSecret) }}
  db-url: {{ .Values.database.external.url | quote }}
  {{- end }}
  {{- if .Values.adminSecret }}
  admin-secret: {{ .Values.adminSecret | quote }}
  {{- end }}
{{- end }}
