apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recon.fullname" . }}-config
  labels:
    {{- include "recon.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- $config := deepCopy .Values.config }}
{{- if hasKey .Values "agents" }}
{{- $_ := set $config "agents" .Values.agents }}
{{- end }}
stringData:
  config.yaml: |
    {{- toYaml $config | nindent 4 }}
