apiVersion: v2
name: warden
description: Helm chart for deploying the Warden policy engine
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://raw.githubusercontent.com/projecthelena/charts/main/assets/icon.png
home: https://github.com/projecthelena/charts
sources:
  - https://github.com/projecthelena/charts
keywords:
  - policy
  - finops
  - kubernetes
maintainers:
  - name: Project Helena
    email: jesus@projecthelena.com
